### ISSUE TITLE
I keep having issues with this crashing and my virus protection and windows protection both keep removing it to block it. Ive had 4 alerts go off about this being unsafe.

### ISSUE THREAD

**Issue by PentakillMundo** [lulzsun/blitz-app-adblock#13]

**Comment by lulzsun** [comment]
It is most likely a false positive due to the act of modifying and extracting existing files that is similar to what a virus would do.

Source code is available for you to look through and compile for yourself if you don't feel safe using the compiled release.

**Comment by PentakillMundo** [comment]
Are there any instructions or a tutorial on how to set this up, please?

**Comment by lulzsun** [comment]
If you don't know how to compile it for yourself, I would just recommend you to download the latest release again, but this time temporarily turn off virus protection before running the patcher. 

There is no risk because it is a false positive. (If you can take my word for it). If you still don't trust me, then I would just recommend you to avoid using this.
