### ISSUE TITLE
Update 1.14.10: Closes on startup

### ISSUE THREAD

**Issue by savedatax86x** [lulzsun/blitz-app-adblock#45]
Force closed on the new patch.

**Comment by noecom12** [comment]
I have the same issue :(

**Comment by lulzsun** [comment]
I've just noticed this behavior and unfortunately, I do not know what the issue may be.

It could be something that Blitz/Electron has done to prevent tampering, because even with just extracting the 'app.asar' file without any changes to it causes the same behavior. Or maybe it could be something unrelated.

There are no errors in the logs from what I can tell to help me find out the source of the problem.

I can't promise any fix to the ad blocker anytime soon. I got a lot of other things to do so I don't got the time right now to dive deeper into this issue, and also because I currently have no leads on why this happening.

If anyone is experienced in Electron apps, feel free to help out.

**Comment by yr0-lab** [comment]
Hello ! 

It's currently blocked, you can get Blitz to work again by reinstalling. I cleaned blitz-folders at %applocaldata% and %appdata%. (Follow step 3 and 4 : https://support.blitz.gg/hc/en-us/articles/360033859312-Clean-Re-installation)

I tried patching again without success.

**Comment by MrBargz** [comment]
> I've just noticed this behavior and unfortunately, I do not know what the issue may be.
> 
> It could be something that Blitz/Electron has done to prevent tampering, because even with just extracting the 'app.asar' file without any changes to it causes the same behavior. Or maybe it could be something unrelated.
> 
> There are no errors in the logs from what I can tell to help me find out the source of the problem.
> 
> I can't promise any fix to the ad blocker anytime soon. I got a lot of other things to do so I don't got the time right now to dive deeper into this issue, and also because I currently have no leads on why this happening.
> 
> If anyone is experienced in Electron apps, feel free to help out.

This is my log app after patch:
info [2021-5-6 18:17:49] Process ARGS
info [2021-5-6 18:17:49] \AppData\Local\Programs\Blitz\Blitz.exe
info [2021-5-6 18:17:49] Checking for update
ERR! [2021-5-6 18:17:49] Couldn't copy over partial or all files from \AppData\Local\Programs\Blitz\resources\binaries : Error: EPERM: operation not permitted, unlink '\AppData\Roaming\Blitz\blitz-deps\1.14.10\index.node'
info [2021-5-6 18:17:50] Update for version 1.14.10 is not available (latest version: 1.14.10, downgrade is disallowed).
info [2021-5-6 18:17:50] Booting Blitz from  file:///C:/Users/user/AppData/Local/Programs/Blitz/resources/app.asar/src/web/landing.html?redirect=https://blitz.gg/app/1.14.10
info [2021-5-6 18:17:52] [AutoUpdater] Initializing
info [2021-5-6 18:17:52] Checking for update
info [2021-5-6 18:17:52] Loading module from  \AppData\Roaming\Blitz\blitz-deps\1.14.10\blitz_core.node
info [2021-5-6 18:17:52] Launched by User
info [2021-5-6 18:17:52] Blitz was NOT pinned
info [2021-5-6 18:17:52] Update for version 1.14.10 is not available (latest version: 1.14.10, downgrade is disallowed).

is this it posible the problem? 
https://github.com/electron/electron/issues/2284

**Comment by L0rdH4x0r** [comment]
probably use pi-hole :)

**Comment by promarcel** [comment]
Since the latest version of Blitz (1.14.15), I just got the message, the current version is not supported.

```Current Blitz version caused patch comparison check to fail. Look for a new patcher release or create a new issue on Github!```

Does this belong to this issue too?

**Comment by lulzsun** [comment]
The patch comparison failing means there were some lines of code changed where the patcher modifies.

This issue needs to be figured out before that could be fixed, because it will close on startup regardless if the patch comparison passes. 

(Patching is currently not working at all because any modifications to the Blitz client will close on startup)

**Comment by lulzsun** [comment]
It appears this has stopped happening on the latest update. I have updated the release for the latest update. Closing this for now.
