### ISSUE TITLE
Can't use it

### ISSUE THREAD

**Issue by HambaGlizzy** [lulzsun/blitz-app-adblock#69]
I have no idea what's wrong.
I don't have a .exe file 
And when I try and open 
blitz-app-adblock-win
It will open console and then: 

Checking for Blitz...
win32
Extracting app.asar...
Downloading ad & tracking filters...
Patching...

Error: Current Blitz version doesn't contain the given injection context.
    at Object.modifyFileAfterContext (G:\snapshot\blitz-app-adblock\io.js)
    at start (G:\snapshot\blitz-app-adblock\blitz-app-adblock.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Press ENTER to quit...

What do I do?

**Comment by lulzsun** [comment]
As mentioned in issue #66, this issue will not be fixed, because there is already a bigger issue (#56) that causes Blitz to crash on startup even with a successful injection context.

There are no current plans from me to fix this.

**Comment by HambaGlizzy** [comment]
So how do I use it?

**Comment by lulzsun** [comment]
You don't, because it doesn't work since it will crash Blitz. There are no plans to fix this.

**Comment by HambaGlizzy** [comment]
So does that mean you given up on the adblock for blitz project.
If so that's ur choice and cool.
I just wanna know.

**Comment by lulzsun** [comment]
This project is open for collaborations, meaning that anyone is able to contribute to fixing this Blitz adblocker.

I don't want to say that I have given up on this project, I've just lost interest in maintaining it, but I've still kept it public for anyone who wants to try to fix it themselves, or even give any insightful information to the related issues so that maybe some day it can be fixed.

But if you want a simple answer, then yes I have given up on this project. 

It's possible that it can be fixed by other people, which is why I have left this project open.

**Comment by HambaGlizzy** [comment]
Welp this Is completely your choice,

I wish you luck In your next projects.

Much love <3
