### ISSUE TITLE
No EXE

### ISSUE THREAD

**Issue by ChocoKrave** [lulzsun/blitz-app-adblock#9]
When I download the latest release there's no exe to be found
![image](https://user-images.githubusercontent.com/48394980/99716042-9be5c900-2a75-11eb-8c61-b5190964c966.png)
![image](https://user-images.githubusercontent.com/48394980/99716091-abfda880-2a75-11eb-9c71-8676c95d296a.png)

**Comment by lulzsun** [comment]
Here is the [direct link](https://github.com/lulzsun/blitz-app-adblock/releases/download/2.0.3/blitz-app-adblock.zip) to the latest release download.

For future GitHub navigation, make sure to download the release and not the source code. (Looks like you downloaded the source instead of the release).

**Comment by ChocoKrave** [comment]
ah i see thank you very much
